// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MovieCollectionsContext))]
    partial class MovieCollectionsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.AddNewMovie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("AddNewMovies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Marfia",
                            Director = "Francis Ford Coppola",
                            Edited = false,
                            Lent = "Shaun",
                            Notes = "Michael is the real boss",
                            Rating = "R",
                            Title = "The Godfather",
                            Year = 1972
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Action/Adventure",
                            Director = "Jon Watts",
                            Edited = false,
                            Lent = "Thor",
                            Notes = "Peter Parker is Spiderman",
                            Rating = "PG-13",
                            Title = "Spider-Man: No Way Home",
                            Year = 2022
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Action/Adventure",
                            Director = "Robert Schwentke",
                            Edited = true,
                            Lent = "Caden",
                            Notes = "Sanke Eyes can speak!",
                            Rating = "PG-13",
                            Title = "Snake Eyes",
                            Year = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
